image:
  name: cr.d.xiaomi.net/doris/doris:1.2

before_script:
  - ulimit -n 60000
  - echo "Working Directory is $(pwd)"

stages:
  - test
  - build  
  - package

test_be_job:
  stage: test
  script:
    - ./run-ut.sh --run

test_fe_job:
  stage: test
  script:
    - ./run-fe-ut.sh

build_job:
  stage: build
  script:
    - ./make_distribution.sh

package_job:
  only:
    - tags
    - branch-0.12-mdh  
  stage: package
  variables:
    MINOS_CONFIG_FILE: '$CI_PROJECT_DIR/deployment-config/deploy.cfg'
    MINOS2_CONFIG_FILE: '$CI_PROJECT_DIR/deployment/deploy.cfg'
  script:
    - git clone git@git.n.xiaomi.com:teg-devops/minos.git
    - git clone git@git.n.xiaomi.com:teg-devops/deployment-config.git
    - git clone git@git.n.xiaomi.com:teg-devops/deployment.git
    - cd minos && ./build.sh build
    - cd ../ && ./make_distribution.sh  
    - cd minos/client/ && ./package install doris --package_dir=$CI_PROJECT_DIR --version=0.12-branch-mdh  
  when: on_success
